# Using self-hosted runners in a workflow: 
# https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/using-self-hosted-runners-in-a-workflow
# https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/using-self-hosted-runners-in-a-workflow#using-custom-labels-to-route-jobs
# https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/using-self-hosted-runners-in-a-workflow#using-labels-and-groups-to-route-jobs

name: Create Roboshop Infrastructure
on: [workflow_dispatch] #workflow will only run on manual trigger. disabling push runs
jobs:
  #DEV-PLAN:
   # runs-on: self-hosted #using label to route job
    #steps:
     # - uses: actions/checkout@v4 #used to checkout the code
      #- name: Terraform Init
       # run: terraform init -backend-config=env-dev/state.tfvars
      #- name: Terraform Plan
       # run: terraform plan -var-file=env-dev/main.tfvars

  DEV-APPLY:
    runs-on: self-hosted #using label to route job
    #environment: dev
    #needs: DEV-PLAN
    steps:
      - uses: actions/checkout@v4 #used to checkout the code
      - name: Terraform Init
        run: terraform init -backend-config=env-dev/state.tfvars
      - name: Terraform Apply
        run: terraform apply -var-file=env-dev/main.tfvars -auto-approve -var vault_token=${{ secrets.VAULT_TOKEN }} #variable input taken from env-dev/main.tfvars. var vault_token is being obtained from https://github.com/organizations/sridevopsb80/settings/secrets/actions

#  QA:
#    runs-on: ubuntu-latest
#    environment: qa
#    needs: DEV-APPLY
#    steps:
#      - run: echo Just a Dummy Job
#  UAT:
#    runs-on: ubuntu-latest
#    environment: uat
#    needs: QA
#    steps:
#      - run: echo Just a Dummy Job
#  PROD:
#    runs-on: self-hosted #using label to route job
#    environment: prod
#    needs: UAT
#    steps:
#      - uses: actions/checkout@v4 #used to checkout the code
#      - name: Terraform Init
#        run: terraform init -backend-config=env-prod/state.tfvars